### PR TITLE
a few small fixes

### PR DESCRIPTION
**Pull request by kiliankoe**

### CODE REVIEW

**Comment by MarauderXtreme** [comment]
You should not had deleted the headline from the last block in the sidebar. Now we are there with an empty headline. Very bad design. You should not do this.

**Comment by kiliankoe** [comment]
Yeah... They're not sponsors though, it looks better and is keeping the design from the old version.

**Comment by MarauderXtreme** [comment]
But then fix it correctly and don't just "hack" something together. Write a check arround the <h4>. This would've been the correct way.
I know that there wasn't a headline in the old one but here we got an empty headline. Argh.

**Comment by kiliankoe** [comment]
I'm seriously failing to the see the issue. Everything looks fine (besides the CSS still being a mess and nowhere close to being finished) and hardcoding a headline that might as well not be there sure seems like a great suggestion :+1:

**Comment by MarauderXtreme** [comment]
Please have a look at 695fbb579a9545e0418b7cbd5e6f5b9ba74c74be. Maybe this will show what I have meant.
Just because the website looks quite fine doesn't mean that the HTML is correct. You can try and evaluate the website with some kind of HTML validator. This empty h4 will get you at least a warning that can be easily avoided.
No one has hardcoded a headline. There only wasn't a check if there is a value.
At last what has the CSS to do with the discussion about this pull request. If there is a problem please make a separate issue or even better fix it by yourself and make another pull request. We're doing our best in bringing the new website as close as possible to the old layout without messing up the HTML.

**Pull request merged**
